services:
  pos-gen-lead-visualiser:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    ports:
      - "${HOST_PORT:-7888}:${CONTAINER_PORT:-80}"
    restart: unless-stopped
